railway_app/config/routes.rb
Rails.application.routes.draw do
  devise_for :users do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end

  resources :tickets, only: %i[create show new index destroy]

  resource :search do
    patch :buy_ticket
    post :find_train
    get :show_ticket
  end

  namespace :admin do
    resources :trains do
      resources :carriages, shallow: true
    end
    resources :railway_stations do
      patch :update_position, on: :member
    end
    resources :tickets, only: %i[index show destroy edit]
    resources :routes
  end
  get 'welcome/index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'searches#show'

end

railway_app/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

railway_app/app/models/carriage.rb
class Carriage < ApplicationRecord
  belongs_to :train

  validates :number, presence: true, uniqueness: { scope: :train_id }
  before_validation  :set_number

  scope :coupe, -> { where(type: 'CoupeCarriage') }
  scope :economy, -> { where(type: 'EconomyCarriage') }
  scope :sleeper, -> { where(type: 'SleeperCarriage') }
  scope :seater, -> { where(type: 'SeaterCarriage') }

  default_scope { order(number: :asc) }
  scope :desc, -> { reorder(number: :desc) }
  protected

  def set_number
    self.number = rand(100)
  end
end

railway_app/app/models/coupe_carriage.rb
class CoupeCarriage < Carriage
  validates :upper_places_amount, :down_places_amount, presence: true
end

railway_app/app/models/economy_carriage.rb
class EconomyCarriage < Carriage
  validates :down_places_amount, :upper_places_amount,
            :side_down_places_amount, :side_upper_places_amount, presence: true
end

railway_app/app/models/railway_station.rb
class RailwayStation < ApplicationRecord
  validates :title, presence: true

  has_many :trains
  has_many :railway_stations_routes
  has_many :routes, through: :railway_stations_routes

  scope :asc, -> { order('railway_stations_routes.station_position') }

  def update_position(route, position)
    station_route = station_route(route)
    station_route&.update(station_position: position)
  end

  def position_in(route)
    station_route(route).try(:station_position)
  end

  def arrival_time(route)
    station_route(route).try(:arrival_time)
  end

  def departure_time(route)
    station_route(route).try(:departure_time)
  end

  def station_route(route)
    @station_route ||= railway_stations_routes.where(route: route).first
  end
end

railway_app/app/models/railway_stations_route.rb
class RailwayStationsRoute < ApplicationRecord
  belongs_to :railway_station
  belongs_to :route

  validates :railway_station_id, uniqueness: { scope: :route_id }
  validates :station_position, uniqueness: { scope: :route_id }

  scope :set_station, ->(station_id) { where("railway_station_id=(#{station_id})") }
end

railway_app/app/models/route.rb
class Route < ApplicationRecord
  validates :name, presence: true

  has_many :railway_stations_routes
  has_many :railway_stations, through: :railway_stations_routes
  has_many :trains

  scope :route_with_station, ->(station_id) { joins('railway_stations_routes').where("railway_stations_routes.railway_station_id=(#{station_id})") }

end

railway_app/app/models/seater_carriage.rb
class SeaterCarriage < Carriage
  validates :seating_places_amount, presence: true
end

railway_app/app/models/sleeper_carriage.rb
class SleeperCarriage < Carriage
  validates :down_places_amount, presence: true
end

railway_app/app/models/ticket.rb
class Ticket < ApplicationRecord
  belongs_to :train
  belongs_to :user

  after_create :send_buying_notification
  before_destroy :send_destroying_notification

  private

  def send_buying_notification
    TicketsMailer.buy_ticket(self.user,self).deliver_now
  end

  def send_destroying_notification
    TicketsMailer.destroy_ticket(self.user,self).deliver_now
  end
end

railway_app/app/models/train.rb
class Train < ApplicationRecord
  validates :number, presence: true

  belongs_to :current_station, class_name: 'RailwayStation', foreign_key: :current_station_id
  belongs_to :route
  has_many :tickets
  has_many :carriages

  def count_places(carriage_type, *places_types)
    places_counter = 0
    carriages.each do |carriage|
      next unless carriage.type == carriage_type

      places_types.each do |place_type|
        places_counter += carriage.method("#{place_type}".to_sym).call
      end
    end
    places_counter
  end
end

railway_app/app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable
  #validates :name, presence: true

  has_many :tickets
end

railway_app/app/controllers/admin/routes_controller.rb
class Admin::RoutesController < Admin::BaseController
  before_action :set_route, only: %i[show edit destroy update]

  def index
    @routes = Route.all
  end

  def show; end

  def new
    @route = Route.new
  end

  def create
    @route = Route.new(route_params)

    if @route.save
      redirect_to @route
    else
      render :new
    end
  end

  def edit; end

  def update
    if @route.update(route_params)
      redirect_to admin_route_path(@route)
    else
      render :edit
    end
  end

  def destroy
    @route.destroy
    redirect_to admin_routes_path
  end

  private

  def set_route
    @route = Route.find(params[:id])
  end

  def route_params
    params.require(:route).permit(:name, railway_station_ids: [])
  end
end

railway_app/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

railway_app/app/controllers/searches_controller.rb
class SearchesController < ApplicationController

  def show; end

  def create
    @relations = RailwayStationsRoute.all
    @ticket = Ticket.new
    @routes = []
    first_stations = @relations.set_station(params[:railway_station_id1])
    second_stations = @relations.set_station(params[:railway_station_id2])
    first_stations.each do |first_station|
      second_stations.each do |second_station|
        if first_station.route_id == second_station.route_id &&
           first_station.station_position < second_station.station_position
          @routes << Route.all.where("id=#{first_station.route_id}")
        end
      end
    end
    @routes
  end
end

railway_app/app/controllers/tickets_controller.rb
class TicketsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_ticket, only: %i[destroy show]

  def show
    @train = Train.find(@ticket.train_id)
  end

  def new
    @ticket = current_user.tickets.new
    params[:train_ids].split(' ').map(&:to_i).each do |train_id|
      @trains ||= []
      @trains << Train.find(train_id)
    end
    @trains
  end

  def create
    @ticket = current_user.tickets.new(ticket_params)
    if @ticket.save
      redirect_to @ticket
    else
      render :new
    end
  end

  def index
    @tickets = current_user.tickets.all
  end

  def destroy
    @ticket.destroy
    redirect_to tickets_path
  end

  private

  def set_ticket
    @ticket = Ticket.find(params[:id])
  end

  def ticket_params
    params.require(:ticket).permit(:id, :train_id, :name, :surname, :passport_id)
  end
end

railway_app/app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

railway_app/app/helpers/application_helper.rb
module ApplicationHelper
end

railway_app/app/helpers/index_helper.rb
module IndexHelper
end

railway_app/app/helpers/railway_stations_helper.rb
module RailwayStationsHelper
end

railway_app/app/helpers/trains_helper.rb
module TrainsHelper
end

railway_app/app/helpers/welcome_helper.rb
module WelcomeHelper
end

railway_app/app/views/admin/routes/_form.html.erb
<%= form_for [:admin, @route] do |form| %>
  <%= render 'common/errors', resource: @route %>
  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :railway_station_ids, 'Railway Station' %>
    <%= form.collection_select :railway_station_ids, RailwayStation.all, :id, :title, {}, { multiple:true } %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>

<% end %>

railway_app/app/views/admin/routes/_route.html.erb
<tr>
  <td><%= route.name %></td>
  <td><%= link_to 'Show', admin_route_path(route) %></td>
  <td><%= link_to 'Edit', edit_admin_route_path(route) %></td>
  <td><%= link_to 'Destroy', admin_route_path(route), method: :delete, data: { confirm: 'Are you sure?' } %></td>
</tr>

railway_app/app/views/admin/routes/edit.html.erb
<h1>Editing Route</h1>

<%= render 'form' %>

<%= link_to 'Show', admin_route_path(@route) %> |
<%= link_to 'Back', admin_routes_path %>

railway_app/app/views/admin/routes/index.html.erb
<h1>Routes</h1>

<table>
  <thead>
  <tr>
    <th>Name</th>
    <th colspan="3"></th>
  </tr>
  </thead>

  <tbody>
    <%= render @routes %>
  </tbody>
</table>

<br>

<%= link_to 'New Route', new_admin_route_path(@routes) %>

railway_app/app/views/admin/routes/new.html.erb
<h1>New Route</h1>

<%= render 'form' %>

<%= link_to 'Back', admin_routes_path %>

railway_app/app/views/admin/routes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @route.name %>
</p>

<p>
  <strong>Stations:</strong>

  <% if !@route.railway_stations.nil? || !@route.railway_stations == [] %>
  <table>
    <thead>
    <tr>
      <td width="100px">Title</td>
      <td>Position</td>
    </tr>
    </thead>
    <% @route.railway_stations.asc.each do |station| %>
    <tr>
      <td><%= station.title %></td>
      <td>
        <%= form_tag update_position_admin_railway_station_path(station), method: :patch do %>
          <%= number_field_tag :station_position, station.position_in(@route) %>
          <%= hidden_field_tag :route_id, @route.id %>
          <%= submit_tag 'Update' %>
        <% end %>
      </td>
    </tr>
    <% end %>
  </table>
  <% else %>
    None
  <% end %>

</p>

<%= link_to 'Edit', edit_admin_route_path(@route) %> |
<%= link_to 'Back', admin_routes_path %>