railway_app/config/routes.rb
Rails.application.routes.draw do
  devise_for :users do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end

  resources :tickets, only: %i[create show new index destroy]

  resource :search do
    patch :buy_ticket
    post :find_train
    get :show_ticket
  end

  namespace :admin do
    resources :trains do
      resources :carriages, shallow: true
    end
    resources :railway_stations do
      patch :update_position, on: :member
    end
    resources :tickets, only: %i[index show destroy edit]
    resources :routes
  end
  get 'welcome/index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'searches#show'

end

railway_app/app/models/train.rb
class Train < ApplicationRecord
  validates :number, presence: true

  belongs_to :current_station, class_name: 'RailwayStation', foreign_key: :current_station_id
  belongs_to :route
  has_many :tickets
  has_many :carriages

  def count_places(carriage_type, *places_types)
    places_counter = 0
    carriages.each do |carriage|
      next unless carriage.type == carriage_type

      places_types.each do |place_type|
        places_counter += carriage.method("#{place_type}".to_sym).call
      end
    end
    places_counter
  end
end

railway_app/app/controllers/admin/trains_controller.rb
class Admin::TrainsController < Admin::BaseController
  before_action :set_train, only: %i[show edit update destroy]

  # GET /trains
  # GET /trains.json
  def index
    @trains = Train.all
  end

  # GET /trains/1
  # GET /trains/1.json
  def show; end

  # GET /trains/new
  def new
    @train = Train.new
  end

  # GET /trains/1/edit
  def edit; end

  # POST /trains
  # POST /trains.json
  def create
    @train = Train.new(train_params)

    respond_to do |format|
      if @train.save
        format.html { redirect_to admin_train_path(@train), notice: 'Train was successfully created.' }
        format.json { render :show, status: :created, location: @train }
      else
        format.html { render :new }
        format.json { render json: @train.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /trains/1
  # PATCH/PUT /trains/1.json
  def update
    respond_to do |format|
      if @train.update(train_params)
        format.html { redirect_to admin_train_path(@train), notice: 'Train was successfully updated.' }
        format.json { render :show, status: :ok, location: @train }
      else
        format.html { render :edit }
        format.json { render json: @train.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /trains/1
  # DELETE /trains/1.json
  def destroy
    @train.destroy
    respond_to do |format|
      format.html { redirect_to admin_trains_url, notice: 'Train was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_train
    @train = Train.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def train_params
    params.require(:train).permit(:number, :current_station_id, :route_id)
  end
end

railway_app/app/helpers/trains_helper.rb
module TrainsHelper
end

railway_app/app/views/admin/trains/_form.html.erb
<%= form_for [:admin, @train] do |form| %>

  <%= render 'common/errors', resource: @train %>

  <div class="field">
    <%= form.label :number %>
    <%= form.text_field :number %>
  </div>

  <div class="field">
    <%= form.label :current_station %>
    <%= form.collection_select :current_station_id, RailwayStation.all, :id, :title %>
  </div>

  <div class="field">
    <%= form.label :route %>
    <%= form.collection_select :route_id, Route.all, :id, :name %>
  </div>

  <div class="actions">
    <%= submit_tag 'Save' %>
  </div>
<% end %>

railway_app/app/views/admin/trains/_train.html.erb
<tr>
  <td><%= train.number %></td>
  <td><%= link_to 'Show', admin_train_path(train) %></td>
  <td><%= link_to 'Edit', edit_admin_train_path(train) %></td>
  <td><%= link_to 'Destroy', admin_train_path(train), method: :delete, data: { confirm: 'Are you sure?' } %></td>
</tr>

railway_app/app/views/admin/trains/edit.html.erb
<h1>Editing Train</h1>

<%= render 'form', train: @train %>

<%= link_to 'Show', admin_train_path(@train) %> |
<%= link_to 'Back', admin_trains_path %>

railway_app/app/views/admin/trains/index.html.erb
<h1>Trains</h1>

<table>
  <thead>
    <tr>
      <th>Number</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <%= render @trains %>
  </tbody>
</table>

<br>

<%= link_to 'New Train', new_admin_train_path(@train) %>

railway_app/app/views/admin/trains/new.html.erb
<h1>New Train</h1>

<%= render 'form', train: @train %>

<%= link_to 'Back', admin_trains_path %>

railway_app/app/views/admin/trains/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Number:</strong>
  <%= @train.number %>
</p>
<p>
  <strong>On the station:</strong>
  <% if !@train.current_station.nil? %>
    <%= @train.current_station.title %>
  <% else %>
    None
  <% end %>
</p>
<p>
  <strong>Carriages:</strong>
  <% if @train.flag %>
    <% @train.carriages.each do |carriage|  %>
        <%= link_to "Carriage ##{carriage.number} ", admin_carriage_path(carriage) %>
      <% end %>
  <% else %>
    <% @train.carriages.desc.each do |carriage|  %>
      <%= link_to "Carriage ##{carriage.number} ", admin_carriage_path(carriage) %>
    <% end %>
  <% end %>
</p>
<%= @train.count_places('EconomyCarriage', 'down_places_amount') %>
<p>
  <strong>Following the route:</strong>
  <% if !@train.route.nil? %>
    <%= @train.route.name %>
  <% else %>
    None
  <% end %>
</p>

<p><%=link_to 'Add a carriage', new_admin_train_carriage_path(@train) %></p>

<%= link_to 'Edit', edit_admin_train_path(@train) %> |
<%= link_to 'Back', admin_trains_path %>