railway_app/config/routes.rb
Rails.application.routes.draw do
  devise_for :users do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end

  resources :tickets, only: %i[create show new index destroy]

  resource :search do
    patch :buy_ticket
    post :find_train
    get :show_ticket
  end

  namespace :admin do
    resources :trains do
      resources :carriages, shallow: true
    end
    resources :railway_stations do
      patch :update_position, on: :member
    end
    resources :tickets, only: %i[index show destroy edit]
    resources :routes
  end
  get 'welcome/index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'searches#show'

end

railway_app/app/models/railway_station.rb
class RailwayStation < ApplicationRecord
  validates :title, presence: true

  has_many :trains
  has_many :railway_stations_routes
  has_many :routes, through: :railway_stations_routes

  scope :asc, -> { order('railway_stations_routes.station_position') }

  def update_position(route, position)
    station_route = station_route(route)
    station_route&.update(station_position: position)
  end

  def position_in(route)
    station_route(route).try(:station_position)
  end

  def arrival_time(route)
    station_route(route).try(:arrival_time)
  end

  def departure_time(route)
    station_route(route).try(:departure_time)
  end

  def station_route(route)
    @station_route ||= railway_stations_routes.where(route: route).first
  end
end

railway_app/app/controllers/admin/railway_stations_controller.rb
class Admin::RailwayStationsController < Admin::BaseController
  before_action :set_railway_station, only: %i[show edit update destroy update_position]

  # GET /railway_stations
  # GET /railway_stations.json
  def index
    @railway_stations = RailwayStation.all
  end

  # GET /railway_stations/1
  # GET /railway_stations/1.json
  def show; end

  # GET /railway_stations/new
  def new
    @railway_station = RailwayStation.new
  end

  # GET /railway_stations/1/edit
  def edit; end

  # POST /railway_stations
  # POST /railway_stations.json
  def create
    @railway_station = RailwayStation.new(railway_station_params)

    respond_to do |format|
      if @railway_station.save
        format.html { redirect_to admin_railway_station_path(@railway_station) }
        format.json { render :show, status: :created, location: @railway_station }
      else
        format.html { render :new }
        format.json { render json: @railway_station.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /railway_stations/1
  # PATCH/PUT /railway_stations/1.json
  def update
    respond_to do |format|
      if @railway_station.update(railway_station_params)
        format.html { redirect_to admin_railway_station_path(@railway_station), notice: 'Railway station was successfully updated.' }
        format.json { render :show, status: :ok, location: @railway_station }
      else
        format.html { render :edit }
        format.json { render json: @railway_station.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /railway_stations/1
  # DELETE /railway_stations/1.json
  def destroy
    @railway_station.destroy
    respond_to do |format|
      format.html { redirect_to admin_railway_stations_url, notice: 'Railway station was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def update_position
    @route = Route.find(params[:route_id])
    @railway_station.update_position(@route, params[:station_position])
    redirect_to admin_route_path(@route)
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_railway_station
    @railway_station = RailwayStation.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def railway_station_params
    params.require(:railway_station).permit(:title)
  end
end

railway_app/app/helpers/railway_stations_helper.rb
module RailwayStationsHelper
end

railway_app/app/views/admin/railway_stations/_form.html.erb
<%= form_for [:admin, @railway_station] do |form| %>
  <%= render 'common/errors', resource: @railway_station %>
  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

railway_app/app/views/admin/railway_stations/_railway_station.html.erb
<tr>
  <td><%= railway_station.title %></td>
  <td><%= link_to t('common.show'), [:admin, railway_station] %></td>
  <td><%= link_to t('common.edit'), edit_admin_railway_station_path(railway_station) %></td>
  <td><%= link_to t('common.destroy'), admin_railway_station_path(railway_station), method: :delete, data: { confirm: 'Are you sure?' } %></td>
</tr>

railway_app/app/views/admin/railway_stations/edit.html.erb
<h1><% t('.title') %></h1>

<%= render 'form' %>

<%= link_to t('common.show'), admin_railway_station_path(@railway_station) %> |
<%= link_to t('common.back'), admin_railway_stations_path %>

railway_app/app/views/admin/railway_stations/index.html.erb
<h1><%= t('.stations')%></h1>

<table>
  <thead>
    <tr>
      <th><%=t('.title') %></th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <%= render @railway_stations %>
  </tbody>
</table>

<br>

<%= link_to t('.new_station'), new_admin_railway_station_path %>

railway_app/app/views/admin/railway_stations/new.html.erb
<h1><%= t('.title') %></h1>

<%= render 'form' %>

<%= link_to t('common.back'), admin_railway_stations_path %>

railway_app/app/views/admin/railway_stations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong><%=t('.title')%>:</strong>
  <%= @railway_station.title %>
</p>

<%= link_to t('common.edit'), edit_admin_railway_station_path(@railway_station) %> |
<%= link_to t('common.back'), admin_railway_stations_path %>