railway_app/config/routes.rb
Rails.application.routes.draw do
  devise_for :users do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end

  resources :tickets, only: %i[create show new index destroy]

  resource :search do
    patch :buy_ticket
    post :find_train
    get :show_ticket
  end

  namespace :admin do
    resources :trains do
      resources :carriages, shallow: true
    end
    resources :railway_stations do
      patch :update_position, on: :member
    end
    resources :tickets, only: %i[index show destroy edit]
    resources :routes
  end
  get 'welcome/index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'searches#show'

end

railway_app/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

railway_app/app/models/carriage.rb
class Carriage < ApplicationRecord
  belongs_to :train

  validates :number, presence: true, uniqueness: { scope: :train_id }
  before_validation  :set_number

  scope :coupe, -> { where(type: 'CoupeCarriage') }
  scope :economy, -> { where(type: 'EconomyCarriage') }
  scope :sleeper, -> { where(type: 'SleeperCarriage') }
  scope :seater, -> { where(type: 'SeaterCarriage') }

  default_scope { order(number: :asc) }
  scope :desc, -> { reorder(number: :desc) }
  protected

  def set_number
    self.number = rand(100)
  end
end

railway_app/app/models/coupe_carriage.rb
class CoupeCarriage < Carriage
  validates :upper_places_amount, :down_places_amount, presence: true
end

railway_app/app/models/economy_carriage.rb
class EconomyCarriage < Carriage
  validates :down_places_amount, :upper_places_amount,
            :side_down_places_amount, :side_upper_places_amount, presence: true
end

railway_app/app/models/railway_station.rb
class RailwayStation < ApplicationRecord
  validates :title, presence: true

  has_many :trains
  has_many :railway_stations_routes
  has_many :routes, through: :railway_stations_routes

  scope :asc, -> { order('railway_stations_routes.station_position') }

  def update_position(route, position)
    station_route = station_route(route)
    station_route&.update(station_position: position)
  end

  def position_in(route)
    station_route(route).try(:station_position)
  end

  def arrival_time(route)
    station_route(route).try(:arrival_time)
  end

  def departure_time(route)
    station_route(route).try(:departure_time)
  end

  def station_route(route)
    @station_route ||= railway_stations_routes.where(route: route).first
  end
end

railway_app/app/models/railway_stations_route.rb
class RailwayStationsRoute < ApplicationRecord
  belongs_to :railway_station
  belongs_to :route

  validates :railway_station_id, uniqueness: { scope: :route_id }
  validates :station_position, uniqueness: { scope: :route_id }

  scope :set_station, ->(station_id) { where("railway_station_id=(#{station_id})") }
end

railway_app/app/models/route.rb
class Route < ApplicationRecord
  validates :name, presence: true

  has_many :railway_stations_routes
  has_many :railway_stations, through: :railway_stations_routes
  has_many :trains

  scope :route_with_station, ->(station_id) { joins('railway_stations_routes').where("railway_stations_routes.railway_station_id=(#{station_id})") }

end

railway_app/app/models/seater_carriage.rb
class SeaterCarriage < Carriage
  validates :seating_places_amount, presence: true
end

railway_app/app/models/sleeper_carriage.rb
class SleeperCarriage < Carriage
  validates :down_places_amount, presence: true
end

railway_app/app/models/ticket.rb
class Ticket < ApplicationRecord
  belongs_to :train
  belongs_to :user

  after_create :send_buying_notification
  before_destroy :send_destroying_notification

  private

  def send_buying_notification
    TicketsMailer.buy_ticket(self.user,self).deliver_now
  end

  def send_destroying_notification
    TicketsMailer.destroy_ticket(self.user,self).deliver_now
  end
end

railway_app/app/models/train.rb
class Train < ApplicationRecord
  validates :number, presence: true

  belongs_to :current_station, class_name: 'RailwayStation', foreign_key: :current_station_id
  belongs_to :route
  has_many :tickets
  has_many :carriages

  def count_places(carriage_type, *places_types)
    places_counter = 0
    carriages.each do |carriage|
      next unless carriage.type == carriage_type

      places_types.each do |place_type|
        places_counter += carriage.method("#{place_type}".to_sym).call
      end
    end
    places_counter
  end
end

railway_app/app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable
  #validates :name, presence: true

  has_many :tickets
end

railway_app/app/controllers/searches_controller.rb
class SearchesController < ApplicationController

  def show; end

  def create
    @relations = RailwayStationsRoute.all
    @ticket = Ticket.new
    @routes = []
    first_stations = @relations.set_station(params[:railway_station_id1])
    second_stations = @relations.set_station(params[:railway_station_id2])
    first_stations.each do |first_station|
      second_stations.each do |second_station|
        if first_station.route_id == second_station.route_id &&
           first_station.station_position < second_station.station_position
          @routes << Route.all.where("id=#{first_station.route_id}")
        end
      end
    end
    @routes
  end
end

railway_app/app/controllers/tickets_controller.rb
class TicketsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_ticket, only: %i[destroy show]

  def show
    @train = Train.find(@ticket.train_id)
  end

  def new
    @ticket = current_user.tickets.new
    params[:train_ids].split(' ').map(&:to_i).each do |train_id|
      @trains ||= []
      @trains << Train.find(train_id)
    end
    @trains
  end

  def create
    @ticket = current_user.tickets.new(ticket_params)
    if @ticket.save
      redirect_to @ticket
    else
      render :new
    end
  end

  def index
    @tickets = current_user.tickets.all
  end

  def destroy
    @ticket.destroy
    redirect_to tickets_path
  end

  private

  def set_ticket
    @ticket = Ticket.find(params[:id])
  end

  def ticket_params
    params.require(:ticket).permit(:id, :train_id, :name, :surname, :passport_id)
  end
end

railway_app/app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

railway_app/app/helpers/application_helper.rb
module ApplicationHelper
end

railway_app/app/helpers/index_helper.rb
module IndexHelper
end

railway_app/app/helpers/railway_stations_helper.rb
module RailwayStationsHelper
end

railway_app/app/helpers/trains_helper.rb
module TrainsHelper
end

railway_app/app/helpers/welcome_helper.rb
module WelcomeHelper
end

railway_app/app/views/common/_errors.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(resource.errors.count, "error") %> prohibited this resource resource from being saved:</h2>

    <ul>
      <% resource.errors.each do |error| %>
        <li><%= error.full_message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

railway_app/app/views/layouts/admin.html.erb
<!DOCTYPE html>
  <head>
    <title>RailwayApp - Admin</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= link_to t('.home'), welcome_index_path%>
    <%= link_to t('.stations'), admin_railway_stations_path%>
    <%= link_to t('.trains'), admin_trains_path %>
    <%= link_to t('.routes'), admin_routes_path %>
    <%= link_to t('.tickets'), admin_tickets_path %>
    <%= link_to 'Русский', "#{request.env['PATH_INFO']}" + root_path(locale: :ru) %>
    <%= link_to 'English', "#{request.env['PATH_INFO']}" + root_path(locale: :en) %>
    <% if user_signed_in? %>
      <%= link_to t('.log_out'), destroy_user_session_path, method: :delete %>
      <%= t('.account') +': ' + current_user.email %>
    <% else %>
      <%= link_to t('.log_in'), new_user_session_path %>
    <% end %>
  </head>
  <body>
    <p id="notice" class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
<p>
  (с) 2021 Misha Makhnovskyy. Study project in
  <a href = http://www.thinknetica.com >Thinknetica online school</a>
</p>
</html>

railway_app/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "RailwayApp" %></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%#= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%#= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%#= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%#= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%#= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

    <%#= javascript_include_tag "application" %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
    <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.2/html5shiv.min.js" type="text/javascript"></script>
    <![endif]-->
  </head>
  <body>

    <div class="navbar navbar-default navbar-static-top">
      <div class="container">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="#">RailwayApp</a>
        <div class="navbar-collapse collapse navbar-responsive-collapse">
          <ul class="nav navbar-nav">
            <li><%= link_to "Search", search_path  %></li>
            <% if user_signed_in? %>
              <% if current_user.admin? %>
                <li><%= link_to "Admin", admin_railway_stations_path  %></li>
              <% end %>
              <li><%= link_to "#{current_user.email}" %></p></li>
              <li><%= button_to 'Log out', destroy_user_session_path, method: :delete %></li>
            <% else %>
              <li><%= link_to 'Log in', new_user_session_path %></li>
            <% end %>

          </ul>
        </div>
      </div>
    </div>

    <div class="container">
      <div class="row">
        <div class="col-lg-9">
          <%= bootstrap_flash %>
          <%= yield %>
        </div>
      </div><!--/row-->

      <footer>
        <p>&copy; Company 2021</p>
      </footer>

    </div> <!-- /container -->

  </body>
</html>